ci: use download-artifact@v3.
The v4 version appears to have an issue, causing the failure:

Error: Unable to download artifact(s): Artifact not found for name: ...

even though the artifact does exist.